# **Workshop 6: Clean Missing Data**
**คำสั่ง**

1.   ศึกษาวิธีการเติมข้อมูลสูญหายเบื้องต้นต่อไปนี้
2.   ทำการเติมข้อมูลสูญหายทุกตัวแปรด้วยวิธีที่เหมาะสม 
3.   ตั้งชื่อไฟล์ python notebook นี้ในรูปแบบ Lab_06_XXXXXXXXX.ipynb โดย XXXXXXXXX คือ รหัสนักศึกษา
4.   ทำการดาวน์โหลดและส่งไฟล์ Lab_06_650510714.ipynb ที่เว็บไซต์ https://mango-cmu.instructure.com/courses/6152/assignments/51680

In [707]:
import pandas as pd
import numpy as np

In [708]:
# If file is not in the same folder as this notebook
# pd.read_csv("C:\\Users\\CSB307\\Desktop\\Download\\Lab_06\\NFL.csv")
nfl_data = pd.read_csv("NFL.csv")
nfl_data.head()

C:\Users\Christopher French\AppData\Local\Temp\ipykernel_7252\1002027004.py:3: DtypeWarning: Columns (51) have mixed types. Specify dtype option on import or set low_memory=False.
  nfl_data = pd.read_csv("NFL.csv")

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,9/10/2009,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,9/10/2009,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,9/10/2009,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,9/10/2009,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,9/10/2009,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

**Check missing data**

In [710]:
nfl_data.shape # (rows, cols)

(41880, 102)

In [711]:
# get the number of missing data points per column
missing_values_count = nfl_data.isnull().sum() # คำสั่งในการนับ Missing Value ตามคอลัมน์

# look at the # of missing points in the first ten columns
missing_values_count[0:10] # ตอนนี้เราดูแค่ 10 คอลัมน์ เราจะทำยังไงให้ดู Missing Value ได้ครบทุกคอลัมน์

Date               0
GameID             0
Drive              0
qtr                0
down            6409
time              29
TimeUnder          0
TimeSecs          29
PlayTimeDiff      58
SideofField       55
dtype: int64

In [712]:
# how many total missing values do we have?
total_cells = np.product(nfl_data.shape)
total_missing = missing_values_count.sum()

# percent of data that is missing
percent_missing = (total_missing/total_cells) * 100
print(percent_missing)

27.769186471150064

**Drop missing values**

In [714]:
print("Total Records =", nfl_data.shape[0])

Total Records = 41880

In [715]:
# remove all the rows that contain a missing value
nfl_data.dropna() # ลบ rows ที่มี Missing Value

Empty DataFrame
Columns: [Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, PlayTimeDiff, SideofField, yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, desc, PlayAttempted, Yards.Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Safety, Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength, AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher, Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult, Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble, RecFumbTeam, RecFumbPlayer, Sack, Challenge.Replay, ChalReplayResult, Accepted.Penalty, PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty.Yards, PosTeamScore, DefTeamScore, ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team, posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre, HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, ...]
Index: []

[0 rows x 102 columns]

In [716]:
# remove all the rows that contain a missing value in specific columns
nfl_data.dropna(subset=['down'])

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
1,9/10/2009,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,9/10/2009,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,9/10/2009,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,9/10/2009,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009
5,9/10/2009,2009091000,2,1,1.0,13:16,14,3496.0,11.0,TEN,...,NaN,0.558929,0.441071,0.578453,0.421547,0.441071,-0.019524,NaN,NaN,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41875,12/28/2009,2009122800,26,5,3.0,10:27,11,-273.0,38.0,CHI,...,-3.447220,0.531010,0.468990,0.373401,0.626599,0.531010,-0.157609,0.061135,-0.218744,2009
41876,12/28/2009,2009122800,26,5,4.0,10:22,11,-278.0,5.0,CHI,...,NaN,0.373401,0.626599,0.551858,0.448142,0.373401,0.178457,NaN,NaN,2009
41877,12/28/2009,2009122800,27,5,1.0,10:11,11,-289.0,11.0,MIN,...,NaN,0.551858,0.448142,0.622337,0.377663,0.448142,-0.070479,NaN,NaN,2009
41878,12/28/2009,2009122800,27,5,2.0,9:32,10,-328.0,39.0,MIN,...,-2.433674,0.622337,0.377663,0.792653,0.207347,0.377663,-0.170316,0.064783,-0.235099,2009
41879,12/28/2009,2009122800,28,5,1.0,9:21,10,-339.0,11.0,MIN,...,1.860585,0.792653,0.207347,NaN,NaN,0.792653,NaN,-0.093898,NaN,2009

In [717]:
nfl_data.shape # ตอนนี้ inplace = False กล่าวคือ เซตข้อมูลต้นฉบับไม่เปลี่ยนแปลง

(41880, 102)

In [718]:
# remove all columns with at least one missing value
nfl_data.dropna(axis=1)

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,desc,PlayAttempted,Yards.Gained,...,AwayTeam,Timeout_Indicator,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,9/10/2009,2009091000,1,1,15,0,0,R.Bironas kicks 67 yards from TEN 30 to PIT 3....,1,39,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
1,9/10/2009,2009091000,1,1,15,10,5,(14:53) B.Roethlisberger pass short left to H....,1,5,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
2,9/10/2009,2009091000,1,1,15,5,2,(14:16) W.Parker right end to PIT 44 for -3 ya...,1,-3,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
3,9/10/2009,2009091000,1,1,14,8,2,(13:35) (Shotgun) B.Roethlisberger pass incomp...,1,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
4,9/10/2009,2009091000,1,1,14,8,2,(13:27) (Punt formation) D.Sepulveda punts 54 ...,1,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41875,12/28/2009,2009122800,26,5,11,7,3,(10:27) (Shotgun) J.Cutler pass incomplete sho...,1,0,...,MIN,0,2,2,2,2,2,0.0,0.0,2009
41876,12/28/2009,2009122800,26,5,11,7,3,"(10:22) B.Maynard punts 47 yards to MIN 14, Ce...",1,3,...,MIN,0,2,2,2,2,2,0.0,0.0,2009
41877,12/28/2009,2009122800,27,5,11,10,0,(10:11) A.Peterson left tackle to MIN 17 for n...,1,0,...,MIN,0,2,2,2,2,2,0.0,0.0,2009
41878,12/28/2009,2009122800,27,5,10,10,16,(9:32) B.Favre pass short right to A.Peterson ...,1,16,...,MIN,0,2,2,2,2,2,0.0,0.0,2009
41879,12/28/2009,2009122800,28,5,10,10,39,(9:21) J.Cutler pass deep right to D.Aromashod...,1,39,...,MIN,0,2,2,2,2,2,0.0,0.0,2009

**Impute missing data**

In [720]:
# fill all missing with a value
results = nfl_data.fillna(0) # แทนค่า Missing Value ให้เป็น 0
results.isnull().sum()

Date        0
GameID      0
Drive       0
qtr         0
down        0
           ..
Win_Prob    0
WPA         0
airWPA      0
yacWPA      0
Season      0
Length: 102, dtype: int64

In [721]:
results.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,9/10/2009,2009091000,1,1,0.0,15:00,15,3600.0,0.0,TEN,...,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,9/10/2009,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,9/10/2009,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,9/10/2009,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,9/10/2009,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009

In [722]:
# fill missing values in a specific column with a value
results = nfl_data
results['down'] = results['down'].fillna(0) # แทนค่า Missing Value ให้เป็น 0 เฉพาะคอลัมน์ down
results.isnull().sum()

Date            0
GameID          0
Drive           0
qtr             0
down            0
            ...
Win_Prob     2767
WPA           643
airWPA      25919
yacWPA      25943
Season          0
Length: 102, dtype: int64

In [723]:
results.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,9/10/2009,2009091000,1,1,0.0,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,9/10/2009,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,9/10/2009,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,9/10/2009,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,9/10/2009,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

In [724]:
# fill missing values in a specific column with mean
results = nfl_data
results['down'] = results['down'].fillna(results['down'].mean()) # แทนค่า Missing Value ใน down ด้วยค่าเฉลี่ย
results.isnull().sum()

Date            0
GameID          0
Drive           0
qtr             0
down            0
            ...
Win_Prob     2767
WPA           643
airWPA      25919
yacWPA      25943
Season          0
Length: 102, dtype: int64

In [725]:
results.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,9/10/2009,2009091000,1,1,0.0,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,9/10/2009,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,9/10/2009,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,9/10/2009,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,9/10/2009,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

ปฏิบัติการข้อ 1) ให้นักศึกษาเติมข้อมูลสูญหายของตัวแปรทั้งหมดที่มีข้อมูลสูญหาย จะใช้วิธีการใดก็ได้ ตามความเหมาะสม พร้อมเขียนอธิบาย

In [727]:
# Answer here!
# ทำการแบ่งการตรวจสอบและจัดการค่าสูญหายทีละ 10 คอลัมน์ เพื่อความสะดวกในการตรวจสอบลักษณะตัวแปรต่างๆ
nfl_data.isnull().sum()[0:10] # Feature ที่ 1-10
nfl_data.isnull().sum()[10:20] # Feature ที่ 11-20
nfl_data.isnull().sum()[20:30] # Feature ที่ 21-30
nfl_data.isnull().sum()[30:40] # Feature ที่ 31-40
nfl_data.isnull().sum()[40:50] # Feature ที่ 41-50
nfl_data.isnull().sum()[50:60] # Feature ที่ 51-60
nfl_data.isnull().sum()[60:70] # Feature ที่ 61-70
nfl_data.isnull().sum()[70:80] # Feature ที่ 71-80
nfl_data.isnull().sum()[80:90] # Feature ที่ 81-90
nfl_data.isnull().sum()[90:] # Feature ที่ 91-102

nfl_data.head() # ลักษณะของชุดข้อมูลในตอนนี้

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,9/10/2009,2009091000,1,1,0.0,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,9/10/2009,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,9/10/2009,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,9/10/2009,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,9/10/2009,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

In [728]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 1-10 
nfl_data.isnull().sum()[0:10] # พบ Missing Value ใน Feature: time, TimeSecs, PlayTimeDiff, SideofField

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 1-10
nfl_data.iloc[:, 0:10].dtypes 
# object: time, SideofField
# float64: TimeSecs, PlayTimeDiff

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values)
nfl_data["time"] = nfl_data["time"].ffill() # แทนค่าใน Feature time ด้วยค่าเวลาที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับเวลาอยู่ระดับหนึ่ง

nfl_data["TimeSecs"] = nfl_data["TimeSecs"].ffill() # แทนค่าใน Feature TimeSecs ด้วยค่าเวลาที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับเวลาอยู่ระดับหนึ่ง

nfl_data["PlayTimeDiff"] = nfl_data["PlayTimeDiff"].fillna(nfl_data["PlayTimeDiff"].mean()//1) # แทนค่าใน Feature TimeSecs ด้วยค่าเฉลี่ย (Mean) ที่ปัดเศษลง เนื่องจากข้อมูลเป็นเลขจำนวนเต็ม แต่เขียนในรูปทศนิยม

nfl_data["SideofField"] = nfl_data["SideofField"].ffill() # แทนค่าใน Feature SideofField ด้วยชื่อสนามที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับชื่อสนามอยู่ระดับหนึ่ง

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 1-10 อีกครั้ง
nfl_data.isnull().sum()[0:10]

Date            0
GameID          0
Drive           0
qtr             0
down            0
time            0
TimeUnder       0
TimeSecs        0
PlayTimeDiff    0
SideofField     0
dtype: int64

In [729]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 11-20 
nfl_data.isnull().sum()[10:20] # พบ Missing Value ใน Feature: yrdln, yrdline100, GoalToGo, FirstDown, posteam, DefensiveTeam

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 11-20
nfl_data.iloc[:, 10:20].dtypes 
# object: posteam, DefensiveTeam
# float64: yrdln, yrdline100, GoalToGo, FirstDown

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values)
nfl_data["yrdln"] = nfl_data["yrdln"].ffill() # แทนค่าใน Feature yrdln ด้วยค่าที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับเส้นหลา

nfl_data["yrdline100"] = nfl_data["yrdline100"].ffill() # แทนค่าใน Feature yrdline100 ด้วยค่าที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับเส้น 100 หลา

nfl_data["GoalToGo"] = nfl_data["GoalToGo"].fillna(nfl_data["GoalToGo"].mode()[0]) # แทนค่าใน Feature GoalToGo ด้วยค่าฐานนิยม (Mode) เนื่องจากข้อมูลเป็นไปได้แค่ 2 ค่า คือ 0.0 กับ 1.0

nfl_data["FirstDown"] = nfl_data["FirstDown"].fillna(nfl_data["FirstDown"].mode()[0]) # แทนค่าใน Feature FirstDown ด้วยค่าฐานนิยม (Mode) เนื่องจากข้อมูลเป็นไปได้แค่ 2 ค่า คือ 0.0 กับ 1.0

nfl_data["posteam"] = nfl_data["posteam"].ffill() # แทนค่าใน Feature posteam ด้วยค่าที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับชื่อทีม

nfl_data["DefensiveTeam"] = nfl_data["DefensiveTeam"].ffill() # แทนค่าใน Feature DefensiveTeam ด้วยค่าที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับชื่อทีม

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 11-20 อีกครั้ง
nfl_data.isnull().sum()[10:20]

yrdln            0
yrdline100       0
ydstogo          0
ydsnet           0
GoalToGo         0
FirstDown        0
posteam          0
DefensiveTeam    0
desc             0
PlayAttempted    0
dtype: int64

In [730]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 21-30
nfl_data.isnull().sum()[20:30] # พบ Missing Value ใน Feature: ExPointResult, TwoPointConv, DefTwoPoint, PuntResult

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 21-30
nfl_data.iloc[:, 20:30].dtypes 
# object: ExPointResult, TwoPointConv
# float64: DefTwoPoint, PuntResult

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values) ด้วยคำว่า Missing เนื่องจากข้อมูลใน Feature เหล่านี้ มีค่าสูญหายจำนวนมากเกินไป
nfl_data["ExPointResult"] = nfl_data["GoalToGo"].fillna("Missing") # แทนค่าใน Feature ExPointResult 
nfl_data["TwoPointConv"] = nfl_data["TwoPointConv"].fillna("Missing") # แทนค่าใน Feature TwoPointConv
nfl_data["DefTwoPoint"] = nfl_data["DefTwoPoint"].fillna("Missing") # แทนค่า Feature DefTwoPoint
nfl_data["PuntResult"] = nfl_data["PuntResult"].fillna("Missing") # แทนค่า Feature PuntResult

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 21-30 อีกครั้ง
nfl_data.isnull().sum()[20:30]

Yards.Gained     0
sp               0
Touchdown        0
ExPointResult    0
TwoPointConv     0
DefTwoPoint      0
Safety           0
Onsidekick       0
PuntResult       0
PlayType         0
dtype: int64

In [731]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 31-40
nfl_data.isnull().sum()[30:40] # พบ Missing Value ใน Feature: Passer, Passer_ID, PassOutcome, PassLength, PassLocation

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 31-40
nfl_data.iloc[:, 30:40].dtypes 
# object: Passer, Passer_ID, PassOutcome, PassLength, PassLocation

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values) ด้วยคำว่า Missing เนื่องจากข้อมูลใน Feature เหล่านี้ ไม่ได้ระบุชื่อหรือรหัสของผู้ส่งบอล จึงถือว่าไม่ได้ทำการเก็บข้อมูลไว้
nfl_data["Passer"] = nfl_data["Passer"].fillna("Missing") # แทนค่าใน Feature Passer
nfl_data["Passer_ID"] = nfl_data["Passer_ID"].fillna("Missing") # แทนค่าใน Feature Passer_ID
nfl_data["PassOutcome"] = nfl_data["PassOutcome"].fillna("Missing") # แทนค่า Feature PassOutcome
nfl_data["PassLength"] = nfl_data["PassLength"].fillna("Missing") # แทนค่า Feature PassLength
nfl_data["PassLocation"] = nfl_data["PassLocation"].fillna("Missing") # แทนค่า Feature PassLocation

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 31-40 อีกครั้ง
nfl_data.isnull().sum()[30:40]

Passer                0
Passer_ID             0
PassAttempt           0
PassOutcome           0
PassLength            0
AirYards              0
YardsAfterCatch       0
QBHit                 0
PassLocation          0
InterceptionThrown    0
dtype: int64

In [732]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 41-50
nfl_data.isnull().sum()[40:50] # พบ Missing Value ใน Feature: Interceptor, Rusher, Rusher_ID, RunLocation, RunGap, Receiver, Receiver_ID, ReturnResult

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 41-50
nfl_data.iloc[:, 40:50].dtypes 
# object: Interceptor, Rusher, Rusher_ID, RunLocation, RunGap, Receiver, Receiver_ID, ReturnResult

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values) ด้วยคำว่า Missing เนื่องจากข้อมูลใน Feature เหล่านี้ มีค่าสูญหายจำนวนมากเกินไป
nfl_data["Interceptor"] = nfl_data["Interceptor"].fillna("Missing") # แทนค่าใน Feature Interceptor
nfl_data["Rusher"] = nfl_data["Rusher"].fillna("Missing") # แทนค่าใน Feature Rusher
nfl_data["Rusher_ID"] = nfl_data["Rusher_ID"].fillna("Missing") # แทนค่า Feature Rusher_ID
nfl_data["RunLocation"] = nfl_data["RunLocation"].fillna("Missing") # แทนค่า Feature RunLocation
nfl_data["RunGap"] = nfl_data["RunGap"].fillna("Missing") # แทนค่า Feature RunGap
nfl_data["Receiver"] = nfl_data["Receiver"].fillna("Missing") # แทนค่า Feature Receiver
nfl_data["Receiver_ID"] = nfl_data["Receiver_ID"].fillna("Missing") # แทนค่า Feature Receiver_ID
nfl_data["ReturnResult"] = nfl_data["ReturnResult"].fillna("Missing") # แทนค่า Feature ReturnResult

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 41-50 อีกครั้ง
nfl_data.isnull().sum()[40:50]

Interceptor     0
Rusher          0
Rusher_ID       0
RushAttempt     0
RunLocation     0
RunGap          0
Receiver        0
Receiver_ID     0
Reception       0
ReturnResult    0
dtype: int64

In [733]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 51-60
nfl_data.isnull().sum()[50:60] 
# พบ Missing Value ใน Feature: Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, RecFumbTeam, RecFumbPlayer

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 51-60
nfl_data.iloc[:, 50:60].dtypes 
# object: Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, RecFumbTeam, RecFumbPlayer
# float64: FieldGoalDistance

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values) ด้วยคำว่า Missing เนื่องจากข้อมูลใน Feature เหล่านี้ มีค่าสูญหายจำนวนมากเกินไป
nfl_data["Returner"] = nfl_data["Returner"].fillna("Missing") # แทนค่าใน Feature Returner
nfl_data["BlockingPlayer"] = nfl_data["BlockingPlayer"].fillna("Missing") # แทนค่าใน Feature BlockingPlayer
nfl_data["Tackler1"] = nfl_data["Tackler1"].fillna("Missing") # แทนค่า Feature Tackler1
nfl_data["Tackler2"] = nfl_data["Tackler2"].fillna("Missing") # แทนค่า Feature Tackler2
nfl_data["FieldGoalResult"] = nfl_data["FieldGoalResult"].fillna("Missing") # แทนค่า Feature FieldGoalResult
nfl_data["FieldGoalDistance"] = nfl_data["FieldGoalDistance"].fillna("Missing") # แทนค่า Feature FieldGoalDistance
nfl_data["RecFumbTeam"] = nfl_data["RecFumbTeam"].fillna("Missing") # แทนค่า Feature RecFumbTeam
nfl_data["RecFumbPlayer"] = nfl_data["RecFumbPlayer"].fillna("Missing") # แทนค่า Feature RecFumbPlayer

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 51-60 อีกครั้ง
nfl_data.isnull().sum()[50:60]

Returner             0
BlockingPlayer       0
Tackler1             0
Tackler2             0
FieldGoalResult      0
FieldGoalDistance    0
Fumble               0
RecFumbTeam          0
RecFumbPlayer        0
Sack                 0
dtype: int64

In [734]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 61-70
nfl_data.isnull().sum()[60:70] 
# พบ Missing Value ใน Feature: ChalReplayResult, PenalizedTeam, PenaltyType, PenalizedPlayer, PosTeamScore, DefTeamScore, ScoreDiff

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 61-70
nfl_data.iloc[:, 60:70].dtypes 
# object: ChalReplayResult, PenalizedTeam, PenaltyType, PenalizedPlayer
# float64: PosTeamScore, DefTeamScore, ScoreDiff

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values)
# แทนค่าด้วยคำว่า Missing เนื่องจากข้อมูลใน Feature เหล่านี้ มีค่าสูญหายจำนวนมากเกินไป
nfl_data["ChalReplayResult"] = nfl_data["ChalReplayResult"].fillna("Missing") # แทนค่า Feature ChalReplayResult
nfl_data["PenalizedTeam"] = nfl_data["PenalizedTeam"].fillna("Missing") # แทนค่า Feature PenalizedTeam
nfl_data["PenaltyType"] = nfl_data["PenaltyType"].fillna("Missing") # แทนค่า Feature PenaltyType
nfl_data["PenalizedPlayer"] = nfl_data["PenalizedPlayer"].fillna("Missing") # แทนค่า Feature PenalizedPlayer

# แทนค่าด้วยค่าที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับชื่อทีม
nfl_data["PosTeamScore"] = nfl_data["PosTeamScore"].ffill() # แทนค่าใน Feature PosTeamScore
nfl_data["DefTeamScore"] = nfl_data["DefTeamScore"].ffill() # แทนค่าใน Feature DefTeamScore
nfl_data["ScoreDiff"] = nfl_data["ScoreDiff"].ffill() # แทนค่าใน Feature ScoreDiff

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 61-70 อีกครั้ง
nfl_data.isnull().sum()[60:70]

Challenge.Replay    0
ChalReplayResult    0
Accepted.Penalty    0
PenalizedTeam       0
PenaltyType         0
PenalizedPlayer     0
Penalty.Yards       0
PosTeamScore        0
DefTeamScore        0
ScoreDiff           0
dtype: int64

In [735]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 71-80
nfl_data.isnull().sum()[70:80] # พบ Missing Value ใน Feature: AbsScoreDiff, Timeout_Team

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 71-80
nfl_data.iloc[:, 70:80].dtypes 
# object: Timeout_Team
# float64: AbsScoreDiff

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values)
nfl_data["AbsScoreDiff"] = nfl_data["AbsScoreDiff"].ffill() # แทนค่าใน Feature AbsScoreDiff ด้วยค่าที่อยู่ก่อนหน้า (Forward Fill) เนื่องจากข้อมูลมีการเรียงลำดับชื่อทีม
nfl_data["Timeout_Team"] = nfl_data["Timeout_Team"].fillna("Missing") # แทนค่า Feature Timeout_Team ด้วยคำว่า Missing เนื่องจากมีค่าสูญหายจำนวนมากเกินไป

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 71-80 อีกครั้ง
nfl_data.isnull().sum()[70:80]

AbsScoreDiff                   0
HomeTeam                       0
AwayTeam                       0
Timeout_Indicator              0
Timeout_Team                   0
posteam_timeouts_pre           0
HomeTimeouts_Remaining_Pre     0
AwayTimeouts_Remaining_Pre     0
HomeTimeouts_Remaining_Post    0
AwayTimeouts_Remaining_Post    0
dtype: int64

In [736]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 81-90
nfl_data.isnull().sum()[80:90]
# พบ Missing Value ใน Feature: No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExpPts

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 81-90
nfl_data.iloc[:, 80:90].dtypes 
# float64: No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExpPts

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values) ของ Feature ที่เป็นค่าความน่าจะเป็นด้วยค่าเฉลี่ย (Mean)
nfl_data["No_Score_Prob"] = nfl_data["No_Score_Prob"].fillna(nfl_data["No_Score_Prob"].mean()) # แทนค่าใน Feature No_Score_Prob
nfl_data["Opp_Field_Goal_Prob"] = nfl_data["Opp_Field_Goal_Prob"].fillna(nfl_data["Opp_Field_Goal_Prob"].mean()) # แทนค่าใน Feature Opp_Field_Goal_Prob
nfl_data["Opp_Safety_Prob"] = nfl_data["Opp_Safety_Prob"].fillna(nfl_data["Opp_Safety_Prob"].mean()) # แทนค่าใน Feature Opp_Safety_Prob
nfl_data["Opp_Touchdown_Prob"] = nfl_data["Opp_Touchdown_Prob"].fillna(nfl_data["Opp_Touchdown_Prob"].mean()) # แทนค่าใน Feature Opp_Touchdown_Prob
nfl_data["Field_Goal_Prob"] = nfl_data["Field_Goal_Prob"].fillna(nfl_data["Field_Goal_Prob"].mean()) # แทนค่าใน Feature Field_Goal_Prob
nfl_data["Safety_Prob"] = nfl_data["Safety_Prob"].fillna(nfl_data["Safety_Prob"].mean()) # แทนค่าใน Feature Safety_Prob
nfl_data["Touchdown_Prob"] = nfl_data["Touchdown_Prob"].fillna(nfl_data["Touchdown_Prob"].mean()) # แทนค่าใน Feature Touchdown_Prob
nfl_data["ExpPts"] = nfl_data["ExpPts"].fillna(nfl_data["ExpPts"].mean()) # แทนค่าใน Feature ExpPts

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 81-90 อีกครั้ง
nfl_data.isnull().sum()[80:90]

No_Score_Prob          0
Opp_Field_Goal_Prob    0
Opp_Safety_Prob        0
Opp_Touchdown_Prob     0
Field_Goal_Prob        0
Safety_Prob            0
Touchdown_Prob         0
ExPoint_Prob           0
TwoPoint_Prob          0
ExpPts                 0
dtype: int64

In [737]:
# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 91-102
nfl_data.isnull().sum()[90:]
# พบ Missing Value ใน Feature: EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, yacWPA

# ตรวจสอบประเภทข้อมูลในคอลัมน์ที่ 91-102
nfl_data.iloc[:, 90:].dtypes 
# float64: EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, yacWPA

# แทนค่าข้อมูลสูญหาย (Imputing Missing Values)
# แทนค่าของ Feature ที่เป็นค่าความน่าจะเป็นด้วยค่าเฉลี่ย (Mean)
nfl_data["EPA"] = nfl_data["EPA"].fillna(nfl_data["EPA"].mean()) # แทนค่าใน Feature EPA
nfl_data["Home_WP_pre"] = nfl_data["Home_WP_pre"].fillna(nfl_data["Home_WP_pre"].mean()) # แทนค่าใน Feature Home_WP_pre
nfl_data["Away_WP_pre"] = nfl_data["Away_WP_pre"].fillna(nfl_data["Away_WP_pre"].mean()) # แทนค่าใน Feature Away_WP_pre
nfl_data["Home_WP_post"] = nfl_data["Home_WP_post"].fillna(nfl_data["Home_WP_post"].mean()) # แทนค่าใน Feature Home_WP_post
nfl_data["Away_WP_post"] = nfl_data["Away_WP_post"].fillna(nfl_data["Away_WP_post"].mean()) # แทนค่าใน Feature Away_WP_post
nfl_data["Win_Prob"] = nfl_data["Win_Prob"].fillna(nfl_data["Win_Prob"].mean()) # แทนค่าใน Feature Win_Prob
nfl_data["WPA"] = nfl_data["WPA"].fillna(nfl_data["WPA"].mean()) # แทนค่าใน Feature Win_Prob

# แทนค่าด้วยคำว่า Missing เนื่องจากมีค่าสูญหายจำนวนมากเกินไป
nfl_data["airEPA"] = nfl_data["airEPA"].fillna("Missing") # แทนค่า Feature airEPA 
nfl_data["yacEPA"] = nfl_data["yacEPA"].fillna("Missing") # แทนค่าใน Feature yacEPA
nfl_data["airWPA"] = nfl_data["airWPA"].fillna("Missing") # แทนค่า Feature airWPA
nfl_data["yacWPA"] = nfl_data["yacWPA"].fillna("Missing") # แทนค่าใน Feature yacWPA

# ตรวจสอบข้อมูลสูญหายในคอลัมน์ที่ 91-102 อีกครั้ง
nfl_data.isnull().sum()[90:]

EPA             0
airEPA          0
yacEPA          0
Home_WP_pre     0
Away_WP_pre     0
Home_WP_post    0
Away_WP_post    0
Win_Prob        0
WPA             0
airWPA          0
yacWPA          0
Season          0
dtype: int64

In [765]:
# ตรวจสอบว่าจัดการค่าสูญหายไปทั้งหมดแล้วหรือยัง
print("Remaining Missing Values =", nfl_data.isnull().sum().sum())

Remaining Missing Values = 0